sudo: false
language: go
go:
  - "1.11.x"
  - "1.12.x"
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
    - env GO111MODULE=on go test -covermode=count -coverprofile=coverage.out -v ./...
    - env GO111MODULE=on $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
